### ISSUE TITLE
[Suggestion] Power for increased throwing damage

### ISSUE THREAD

**Issue by Desempregago** [SmushyTaco/Expanded-Trident-Enchanting#1]

**Comment by SmushyTaco** [comment]
The mod is meant to just allow the enchants to be applied which it does.

**Comment by Desempregago** [comment]
But you can't put Power on Tridents, though

**Comment by SmushyTaco** [comment]
Because that wasn't intended

**Comment by Desempregago** [comment]
neither sharpness and smite :P

**Comment by SmushyTaco** [comment]
The mod description literally states "This mod allows you to use Fire Aspect, Knockback, Looting, and all other sword enchantment types on a trident." and sharpness and smite are sword enchantments 🙂
